### ISSUE TITLE
Define common data types

### ISSUE THREAD

**Issue by AndreasWintherMoen** [BarkApp/bark#66]
Assuming it's possible, it would be nice to have data types that exist on both the backend and frontend (mostly DAOs I suppose) in a shared module in the root folder.

**Comment by haakonjacobsen** [comment]
Maybe this **_"BFF pattern"_** can be used. 
![](https://miro.medium.com/max/530/1*laZH8QsjjxXKA4r9ZxCRVA.png)

**Comment by haakonjacobsen** [comment]
Because the frontend and backend are separated, we close this issue for now
